### ISSUE TITLE
CALANGO::retrieve_calanguize_genomes erased files on the target directory.

### ISSUE THREAD

**Issue by Zandorah** [fcampelo/CALANGO#6]
When using retrieve_calanguize_genomes, all the files and directories previously present in the target directory were erased, remaining only the "calanguize_genomes.pl" file that was successfully downloaded. 

The command used was: 
`CALANGO::retrieve_calanguize_genomes("/home/my_username/Documents/", method = "auto", unzip = get0ption("unzip"))`

**Comment by fcampelo** [comment]
Apologies for the ridiculously long delay in solving this. Sorted now in branch Update_2024Sep. Will push to main and update to CRAN soon.
